### PR TITLE
Update flatiron-passport.js

### PR DESCRIPTION
**Pull request by vanthome**
Hi, please have a look a this PR.
It enhances 2 things:
1.) If you don't use sessions, you can now turn it off by 
app.use(fipassport, {session: false});

2.) If you have auth schemes which involve more than on handler like
an OAuth token endpoint for example, you need to consider the callback of flatiron 
and call it accordingly; otherwise only the first handler will get called.

pls. accept if you like.

Thanks,
Thomas

### CODE REVIEW

**Comment by travist** [comment]
Please update your commit message to be more descriptive of what actually changed in this pull request.  

You can do this using `git rebase -i origin/master` pretty easily and then just `reword` that commit message.  

Other than that, this looks pretty good since even if the session setting is `undefined`, this will still maintain existing behavior.

**Comment by vanthome** [comment]
Ok, I try this way so that everyone can read this thread.
I guess the session thing is clear so I'll detail the second part:

Generally there is the possibility to have several functions executed for
a sing route. Unfortunately, this feature is barely documented in flatiron.
For complex auth schemes like OAuth in this example app:

https://github.com/jaredhanson/oauthorize/tree/master/examples

You see that you will need several handlers.
I found this is possible in flatiron like this:

``` javascript
      var routes = {'/oauth2/token': {
                    post: [
                           function(cb) {
                               console.log('1');
                              cb();
                              this.res.emit('next');
                           },
                           function(cb) {
                                console.log('2');
                               cb();
                               this.res.emit('next');
                            },                          
                           function(cb) {
                               console.log('3');
                              cb(false);
                              this.res.emit('next');

                           }                                             
                       ]
                  }           
            }        
            app.router.mount(routes); // Insert this  routing table into the application wide table
```

I've resembled this in fi-passport.

**Comment by pvorb** [comment]
@travist Is something still missing before you'll accept?

**Comment by travist** [comment]
No... looks good to me.  Thanks for the update.

**Comment by vanthome** [comment]
Can you please push this to npm?

**Comment by travist** [comment]
Done.  Sorry about that.

**Pull request merged**
